name: 'dw_kimball'
version: '1.0.0'
config-version: 2

# O 'profile' é o nome da credencial que o dbt usará para conectar ao banco.
# Nós configuraremos isso no K8s futuramente.
profile: 'postgres_lab_dbt'

model-paths: ["models"]
test-paths: ["tests"]

# Configurações de materialização em massa por diretório
models:
  dw_kimball:
    staging:
      +materialized: view
      +schema: kimball_stg
    marts:
      +materialized: table
      +schema: kimball_dw