postgres_lab_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST') }}"
      user: "{{ env_var('DBT_DB_USER') }}"
      password: "{{ env_var('DBT_DB_PASSWORD') }}"
      port: 5432
      database: "{{ env_var('DBT_DB_NAME') }}"
      threads: 4 # Nível de paralelismo para execução simultânea das tabelas